# Generated by Django 5.2.17 on 2026-08-29 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('schema_version', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('publication_state', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('SUSPENDED', 'Suspended')], default='DRAFT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('schema_version', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_actor', models.CharField(max_length=150)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('state', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED_RETRYABLE', 'Failed Retryable'), ('FAILED_FINAL', 'Failed Final')], default='QUEUED', max_length=24)),
                ('candidate_state', models.CharField(choices=[('RECEIVED', 'Received'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('DUPLICATE', 'Duplicate')], default='RECEIVED', max_length=16)),
                ('adapter_revision', models.CharField(max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('failure_message', models.CharField(blank=True, max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('schema_version', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_product_id', models.CharField(max_length=80)),
                ('region', models.CharField(default='KR', max_length=2)),
                ('currency_expectation', models.CharField(default='KRW', max_length=3)),
                ('edition_key', models.SlugField(max_length=80)),
                ('edition_label', models.CharField(max_length=120)),
                ('mapping_state', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAUSED', 'Paused')], default='DRAFT', max_length=16)),
                ('tracking_started_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_products', to='prices.game')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('schema_version', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('code', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=120)),
                ('source_state', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAUSED', 'Paused')], default='DRAFT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationDecision',
            fields=[
                ('schema_version', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_identity', models.CharField(max_length=150)),
                ('subject_type', models.CharField(max_length=40)),
                ('subject_identity', models.CharField(max_length=150)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=16)),
                ('reason', models.TextField()),
                ('immutable_input_identity', models.CharField(max_length=64)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['decided_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('schema_version', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(max_length=32)),
                ('actor_identity', models.CharField(max_length=150)),
                ('event_kind', models.CharField(max_length=64)),
                ('subject_identity', models.CharField(max_length=150)),
                ('immutable_input_identity', models.CharField(max_length=128)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Success'), ('REJECTED', 'Rejected'), ('DUPLICATE', 'Duplicate'), ('FAILED_RETRYABLE', 'Failed Retryable'), ('FAILED_FINAL', 'Failed Final')], max_length=24)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('redaction_status', models.CharField(default='REDACTED', max_length=24)),
                ('related_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='prices.ingestionrun')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='ingestionrun',
            name='store_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='prices.storeproduct'),
        ),
        migrations.CreateModel(
            name='SourceReceipt',
            fields=[
                ('schema_version', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_method', models.CharField(max_length=8)),
                ('normalized_url', models.URLField(max_length=500)),
                ('fetched_at', models.DateTimeField()),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_sha256', models.CharField(max_length=64)),
                ('receipt_identity', models.CharField(max_length=64, unique=True)),
                ('source_revision_metadata', models.JSONField(default=dict)),
                ('redaction_status', models.CharField(default='REDACTED', max_length=24)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='prices.ingestionrun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceObservation',
            fields=[
                ('schema_version', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observation_identity', models.CharField(max_length=64, unique=True)),
                ('currency', models.CharField(max_length=3)),
                ('current_amount', models.BigIntegerField()),
                ('regular_amount', models.BigIntegerField(blank=True, null=True)),
                ('discount_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source_observed_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('store_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='prices.storeproduct')),
                ('source_receipt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='accepted_observation', to='prices.sourcereceipt')),
            ],
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='prices.store'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='mapping_approval_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prices.verificationdecision'),
        ),
        migrations.AddField(
            model_name='store',
            name='terms_approval_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='prices.verificationdecision'),
        ),
        migrations.CreateModel(
            name='PublishedPriceProjection',
            fields=[
                ('schema_version', models.PositiveSmallIntegerField(default=1, editable=False)),
                ('store_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='published_price', serialize=False, to='prices.storeproduct')),
                ('currency', models.CharField(max_length=3)),
                ('current_amount', models.BigIntegerField()),
                ('regular_amount', models.BigIntegerField(blank=True, null=True)),
                ('discount_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('observed_low_amount', models.BigIntegerField()),
                ('tracking_started_at', models.DateTimeField()),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('latest_observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='latest_for_projections', to='prices.priceobservation')),
                ('observed_low_observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='low_for_projections', to='prices.priceobservation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ingestionrun',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['QUEUED', 'RUNNING'])), fields=('store_product',), name='one_active_run_per_store_product'),
        ),
        migrations.AddConstraint(
            model_name='priceobservation',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'KRW')), name='observation_currency_krw'),
        ),
        migrations.AddConstraint(
            model_name='priceobservation',
            constraint=models.CheckConstraint(condition=models.Q(('current_amount__gte', 0)), name='current_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='priceobservation',
            constraint=models.CheckConstraint(condition=models.Q(('regular_amount__isnull', True), ('regular_amount__gte', models.F('current_amount')), _connector='OR'), name='regular_not_below_current'),
        ),
        migrations.AddConstraint(
            model_name='priceobservation',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__isnull', True), ('discount_percent__range', (0, 100)), _connector='OR'), name='discount_percentage_bounded'),
        ),
        migrations.AddConstraint(
            model_name='storeproduct',
            constraint=models.UniqueConstraint(fields=('store', 'external_product_id', 'region', 'edition_key'), name='unique_store_product_identity'),
        ),
        migrations.AddConstraint(
            model_name='storeproduct',
            constraint=models.CheckConstraint(condition=models.Q(('region', 'KR')), name='mvp_region_is_kr'),
        ),
        migrations.AddConstraint(
            model_name='storeproduct',
            constraint=models.CheckConstraint(condition=models.Q(('currency_expectation', 'KRW')), name='mvp_currency_is_krw'),
        ),
        migrations.AddConstraint(
            model_name='publishedpriceprojection',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'KRW')), name='projection_currency_krw'),
        ),
        migrations.AddConstraint(
            model_name='publishedpriceprojection',
            constraint=models.CheckConstraint(condition=models.Q(('current_amount__gte', 0)), name='projection_current_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='publishedpriceprojection',
            constraint=models.CheckConstraint(condition=models.Q(('observed_low_amount__gte', 0)), name='projection_low_nonnegative'),
        ),
    ]
